# More fixes on the autoconf
git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/flowClust@31253 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1208,8 +1208,7 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-blas             use system gsl BLAS library (if available), or
-                          specify it [no]
+  --with-blas             use system gsl BLAS library (if available)
   --with-gsl-prefix=PFX   Prefix where GSL is installed (optional)
   --with-gsl-exec-prefix=PFX Exec prefix where GSL is installed (optional)
 
@@ -1645,11 +1644,18 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-# : ${R_HOME=`R RHOME`}
-# if test -z "${R_HOME}"; then
-#   echo "could not determine R_HOME"
-#   exit 1
-# fi
+# determine RHOME
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+
+## pick up compiler as will be used by R CMD INSTALL/SHLIB
+if test -n "${R_HOME}"; then
+  CC=`${R_HOME}/bin/R CMD config CC`
+  CFLAGS=`${R_HOME}/bin/R CMD config CFLAGS`
+fi
 
 ## BLAS.
 
@@ -1657,7 +1663,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 if test "${with_blas+set}" = set; then
   withval=$with_blas; BLAS_LIBS=$with_blas
 else
-  BLAS_LIBS=`-lgslcblas`
+  BLAS_LIBS="-lgslcblas"
 fi
 
 
@@ -2806,7 +2812,7 @@ fi
   if test "x$no_gsl" = x ; then
      { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-     LIBS="${LIBS} ${BLAS_LIBS} -lgsl"
+     LIBS="${LIBS} -lgsl ${BLAS_LIBS} -lm"
   else
      { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
